-- MySQL Script generated by MySQL Workbench
-- Tue Dec 10 20:08:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myBlog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myBlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myBlog` DEFAULT CHARACTER SET utf8 ;
USE `myBlog` ;

-- -----------------------------------------------------
-- Table `myBlog`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`users` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` ENUM('admin', 'user') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`posts` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(500) NOT NULL,
  `updated_at` DATE NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`rel_users_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`rel_users_posts` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`rel_users_posts` (
  `users_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  `relation` ENUM('owner', 'subscriber') NOT NULL,
  PRIMARY KEY (`users_id`, `posts_id`),
  INDEX `fk_rel_user_posts_posts_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_rel_user_posts_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk__rel_users_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `myBlog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rel_users_posts_posts`
    FOREIGN KEY (`posts_id`)
    REFERENCES `myBlog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`comments` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` DATE NOT NULL,
  `message` VARCHAR(100) NOT NULL,
  `coments_id` INT NULL,
  PRIMARY KEY (`id`, `posts_id`),
  INDEX `fk_comments_posts_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_comments_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_comments_comments_idx` (`coments_id` ASC) INVISIBLE,
  CONSTRAINT `fk_comments_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `myBlog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_posts`
    FOREIGN KEY (`posts_id`)
    REFERENCES `myBlog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_comments`
    FOREIGN KEY (`coments_id`)
    REFERENCES `myBlog`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
