-- MySQL Script generated by MySQL Workbench
-- Sun Dec 15 11:21:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myBlog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myBlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myBlog` DEFAULT CHARACTER SET utf8 ;
USE `myBlog` ;

-- -----------------------------------------------------
-- Table `myBlog`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`users` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` ENUM('admin', 'user') NOT NULL default 'user',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`themes` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`themes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tema_UNIQUE` (`tema` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`posts` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(75) NOT NULL,
  `message` VARCHAR(5000) NOT NULL,
  `updated_at` DATETIME NULL ON UPDATE current_timestamp,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `themes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `themes_id`),
  INDEX `fk_posts_themes1_idx` (`themes_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_themes1`
    FOREIGN KEY (`themes_id`)
    REFERENCES `myBlog`.`themes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`rel_users_posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`rel_users_posts` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`rel_users_posts` (
  `users_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  `relation` ENUM('owner', 'subscriber') NOT NULL,
  PRIMARY KEY (`users_id`, `posts_id`),
  INDEX `fk_rel_user_posts_posts_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_rel_user_posts_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `myBlog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_posts_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `myBlog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`comments` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posts_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `message` VARCHAR(100) NOT NULL,
  `comments_id` INT NULL,
  PRIMARY KEY (`id`, `posts_id`),
  INDEX `fk_comments_posts_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_comments_users_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_comments_comments_idx` (`comments_id` ASC) INVISIBLE,
  CONSTRAINT `fk_users_has_posts1_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `myBlog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_posts1_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `myBlog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coments_coments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `myBlog`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`chats` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`chats` (
  `user1_id` INT NOT NULL,
  `user2_id` INT NOT NULL,
  `isBlocked` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user1_id`, `user2_id`),
  INDEX `fk_users_has_users_users2_idx` (`user2_id` ASC) VISIBLE,
  INDEX `fk_users_has_users_users1_idx` (`user1_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`user1_id`)
    REFERENCES `myBlog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`user2_id`)
    REFERENCES `myBlog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`messages` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`messages` (
  `chat_user1_id` INT NOT NULL,
  `chat_user2_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `message` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`chat_user1_id`, `chat_user2_id`),
  INDEX `fk_Messages_chat1_idx` (`chat_user1_id` ASC, `chat_user2_id` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_chat1`
    FOREIGN KEY (`chat_user1_id` , `chat_user2_id`)
    REFERENCES `myBlog`.`chats` (`user1_id` , `user2_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myBlog`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myBlog`.`questions` ;

CREATE TABLE IF NOT EXISTS `myBlog`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(75) NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `users_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `myBlog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
commit;